### ISSUE TITLE
Error adding extension element to UserTask

### ISSUE THREAD

**Issue by izilotti** [camunda/camunda-bpmn-model#10]
The exception below is thrown when I add the following lines to the code that creates a `ModelInstance`. In essence I'm trying to add an ExtensionElements element that contains Properties to a UserTask. To me the exception is not making to much sense, as it seems to be an issue validating the model. I'm using Camunda 7.3.0.

```java
            UserTask userTask = modelInstance.newInstance(UserTask.class);
            ExtensionElements extensionElements = modelInstance.newInstance(ExtensionElements.class);
            for (Map.Entry<String, String> pe : properties.entrySet()) {
                Property property = modelInstance.newInstance(Property.class);
                property.setAttributeValue("name", pe.getKey());
                property.setAttributeValue("value", pe.getValue());
                extensionElements.addChildElement(property);
            }
            flowElement.addChildElement(extensionElements);
```

**Stack trace:**
```
org.camunda.bpm.model.xml.ModelValidationException: DOM document is not valid

	at org.camunda.bpm.model.xml.impl.parser.AbstractModelParser.validateModel(AbstractModelParser.java:95)
	at org.camunda.bpm.model.bpmn.Bpmn.doValidateModel(Bpmn.java:267)
	at org.camunda.bpm.model.bpmn.Bpmn.doWriteModelToOutputStream(Bpmn.java:254)
	at org.camunda.bpm.model.bpmn.Bpmn.doWriteModelToFile(Bpmn.java:243)
	at org.camunda.bpm.model.bpmn.Bpmn.writeModelToFile(Bpmn.java:139)
Caused by: org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element 'property'. One of '{WC[##other:"http://www.omg.org/spec/BPMN/20100524/MODEL"]}' is expected.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:458)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3237)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1796)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:746)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.beginNode(DOMValidatorHelper.java:277)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:244)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:190)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:109)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at org.camunda.bpm.model.xml.impl.parser.AbstractModelParser.validateModel(AbstractModelParser.java:90)
	... 31 more
```

**Comment by menski** [comment]
Hi,

sorry for the late response. Where you able to solve your problem? The `Property.class` is not a Camunda Extension Element. Which extension element do you want to add?

Cheers,
Sebastian

**Comment by izilotti** [comment]
Hello Sebastian,

You are right. Got the problem sorted out using ModelElementInstance instead
of Property.class.

Best,
Ivan
